### ISSUE TITLE
addOrganism commonName parameter

### ISSUE THREAD

**Issue by epaule** [galaxy-genome-annotation/python-apollo#1]
Hia,

I think there is some unintentional lower_casing in the cli, which breaks the addOrganism parameter commonName.

`./arrow --verbose organisms addOrganism trichuris2 /data/trichuris2
cli() got an unexpected keyword argument 'commonname'`

it doesn't fire of a request, so it should be somewhere in the cli code , but for the life of me, I can't find it.

**Comment by hexylena** [comment]
Hi @epaule, I'm afraid I can't reproduce this. How have you installed arrow and would you mind trying to update python-apollo / arrow?

```
$ arrow organisms add_organism testing_HEM /opt/apollo/data/galaxy//164220
{
    "id": 699595,
    "publicMode": false,
    "commonName": "testing_HEM",
    "currentOrganism": true,
    "blatdb": null,
    "species": null,
    "valid": true,
```

**Comment by epaule** [comment]
it is version 3.0

**Comment by epaule** [comment]
seems like add_organism behaves correctly, whereas addOrganism doesn't

to be fair, addOrganism has a Warning: Undocumented Method
so if it doesn't work, maybe we can retire it?

**Comment by hexylena** [comment]
Yep, that's been removed since release 3.0.1 (latest is 3.0.3), for exactly the reasons you've found.
