### ISSUE TITLE
if Shine Dalgarno is attached as evidence it gets rendered as an exon

### ISSUE THREAD

**Issue by nathandunn** [galaxy-genome-annotation/python-apollo#48]
This is treated correctly coming form the UI (Canvas I think), but not using the load_gff3 script. 

This fixed the initial drag up issue: https://github.com/GMOD/Apollo/pull/2516

I think the JSON sent over is correct, but maybe mis-associated with the gene instead of the transcript.

**Comment by MoffMade** [comment]
Just confirmed on our workflows, any evidence that has an associated Shine Dalgarno is using a Canvas feature in the JBrowse/Apollo UI

**Comment by nathandunn** [comment]
Not sure if it will be related to this: https://github.com/GMOD/Apollo/issues/2144

However, it probably has to be that the Shine_dalgarno must be associated at the right level via the python-apollo manipulation.

**Comment by nathandunn** [comment]
Both dragging up and right-click adding with html and canvas produce the correct output:

![image](https://user-images.githubusercontent.com/751274/106328990-8fc87580-6235-11eb-8aea-6cf78bee9d35.png)

![image](https://user-images.githubusercontent.com/751274/106328996-922acf80-6235-11eb-96c4-091697ab4fc5.png)

**Comment by nathandunn** [comment]
Using: ` arrow annotations load_gff3 shinedalgarno2 test1.gff3`  with gff3:

```
##gff-version 3
##sequence-region ACHIV102_cov_229.2 1 42452
ACHIV102_cov_229.2	.	gene	20958	22306	.	+	.	owner=ndunn@me.com;ID=c2bdb72a-b116-43df-8ca4-fd07a8a46a7e;date_last_modified=2021-01-29;Name=ACHIV102_cov_229.2.orf00043;date_creation=2021-01-29
ACHIV102_cov_229.2	.	mRNA	20958	22306	.	+	.	owner=ndunn@me.com;Parent=c2bdb72a-b116-43df-8ca4-fd07a8a46a7e;ID=14c936aa-a03a-42f5-b03c-9648aa9aa0c5;date_last_modified=2021-01-29;Name=ACHIV102_cov_229.2.orf00043-00002;date_creation=2021-01-29
ACHIV102_cov_229.2	.	Shine_Dalgarno_sequence	20958	20960	.	+	.	Parent=14c936aa-a03a-42f5-b03c-9648aa9aa0c5;ID=d6047ece-fa1e-4429-b9b4-b70c369a8006;Name=d6047ece-fa1e-4429-b9b4-b70c369a8006
ACHIV102_cov_229.2	.	exon	20969	22306	.	+	.	Parent=14c936aa-a03a-42f5-b03c-9648aa9aa0c5;ID=e02f1b38-e5c7-4d92-8d44-89d1599c756f;Name=e02f1b38-e5c7-4d92-8d44-89d1599c756f
ACHIV102_cov_229.2	.	non_canonical_three_prime_splice_site	20969	20969	.	+	.	Parent=14c936aa-a03a-42f5-b03c-9648aa9aa0c5;ID=14c936aa-a03a-42f5-b03c-9648aa9aa0c5-non_canonical_three_prime_splice_site-20968;Name=14c936aa-a03a-42f5-b03c-9648aa9aa0c5-non_canonical_three_prime_splice_site-20968
ACHIV102_cov_229.2	.	CDS	20969	22306	.	+	0	Parent=14c936aa-a03a-42f5-b03c-9648aa9aa0c5;ID=14c936aa-a03a-42f5-b03c-9648aa9aa0c5-CDS;Name=14c936aa-a03a-42f5-b03c-9648aa9aa0c5-CDS
###
```

transfer the shine_dalgarno into an exon:

![image](https://user-images.githubusercontent.com/751274/106329228-f188df80-6235-11eb-9258-79c63c9f9e08.png)

**Comment by nathandunn** [comment]
this should be working now: 
![image](https://user-images.githubusercontent.com/751274/106330530-3dd51f00-6238-11eb-94eb-123cae4258cf.png)
