### ISSUE TITLE
biopython dependency error

### ISSUE THREAD

**Issue by jaspwn** [galaxy-genome-annotation/python-apollo#56]
Hi, I recently installed python-apollo via pip `4.2.13` and I encourntered a dependency error with biopython.

UnknownSeq is a deprecated class in biopython `1.81`

```
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/BCBio/GFF/GFFParser.py", line 34, in <module>
    from Bio.Seq import UnknownSeq
ImportError: cannot import name 'UnknownSeq' from 'Bio.Seq' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Bio/Seq.py) 
```

Not really sure the correct way to fix, but I did it by just getting Bio/Seq.py from biopython '1.79'

**Comment by abretaud** [comment]
Hi,
Yes there's an incompatibilty between bcbio-gff and biopython 1.81, there's an issue descibing that: https://github.com/chapmanb/bcbb/issues/136
The simplest soltion for now is to pin biopython to version 1.80 or lower.
I *hope* there will be a new bcbio-gff release soon to fix this, there are so many projects impacted :(

**Comment by jaspwn** [comment]
Thanks! Thats probably a better fix than the one i implemented.
